// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
	HireDate  pgtype.Date
	Salary    pgtype.Numeric
}
